spring:
  application:
    name: ms-agendador-tarefas

  data:
    mongodb:
      uri: mongodb://admin:12345@localhost:27017/db_agendador?authSource=admin

usuario:
  url:
    localhost:8080

server:
  port: 8081
